version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: threat-intel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: threatintel
      MYSQL_USER: threatuser
      MYSQL_PASSWORD: threatpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - threat-network
    restart: unless-stopped

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: threat-intel-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/threatintel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: threatuser
      SPRING_DATASOURCE_PASSWORD: threatpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - threat-network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: threat-intel-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - threat-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  threat-network:
    driver: bridge
